

pluginManagement {
    repositories {
        maven { url 'https://maven-central.storage-download.googleapis.com/maven2/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url 'https://maven-central.storage-download.googleapis.com/maven2/' }
        mavenCentral()
    }
}

rootProject.name = 'MEEK'